### PR TITLE
Formally add the zlib license

### PR DESCRIPTION
**Pull request by flibitijibibo**
This was established with the internal team but I didn't expect this to grow beyond a thing for MojoShader and by extension FNA/Moonworks, so I never got around to it... now that it's in the org we should probably get to this, and have it all in writing.

@Beyley, @RandyGaul, @leandro-benedet-garcia, @ritalat, do we have your blessing to officially put the zlib license on this?

### CODE REVIEW

**Comment by Beyley** [comment]
sounds good to me!

**Comment by leandro-benedet-garcia** [comment]
Perfectly fine to me.

**Comment by RandyGaul** [comment]
Do it

**Comment by ritalat** [comment]
Fine by me.

**Comment by flibitijibibo** [comment]
Thanks everybody, both for the approval and the work on shadercross! <3

**Pull request merged**
